spring:
  profiles:
    active: local
  application:
    name: settlement

  # Thymeleaf 공통 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL:}

# 초기 더미 데이터 생성용 비밀번호 설정
app:
  init:
    super-admin:
      password: ${INIT_SUPER_ADMIN_PASSWORD:admin1234!}
    common:
      password: ${INIT_COMMON_PASSWORD:user1234!}
